# Generated by Django 3.1.7 on 2021-02-27 09:36

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210226_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_jpeg',
            field=smartfields.fields.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=smartfields.fields.ImageField(blank=True, upload_to='images'),
        ),
    ]
