# Generated by Django 3.1.7 on 2021-02-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210227_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_jpeg',
        ),
    ]
