# Generated by Django 3.1.7 on 2021-02-27 10:24

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_image_jpeg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=smartfields.fields.ImageField(blank=True, height_field=100, upload_to='images', width_field=100),
        ),
    ]
