# Generated by Django 3.1.7 on 2021-02-27 10:56

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210227_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=smartfields.fields.ImageField(blank=True, height_field=100, help_text='Minimal reslution for image: 100x100\nMax resolution for image: 1000x1000', upload_to='images', width_field=100),
        ),
    ]
