# Generated by Django 3.1.7 on 2021-02-27 11:27

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210227_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=smartfields.fields.ImageField(blank=True, help_text='Minimal reslution for image: 100x100\nMax resolution for image: 1000x1000', upload_to='images'),
        ),
    ]
